- name: Create namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_namespace }}"

- name: Create PVC
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-pvc
        namespace: "{{ app_namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

- name: Deploy Redis
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: redis
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: redis
        template:
          metadata:
            labels:
              app: redis
          spec:
            containers:
              - name: redis
                image: "{{ acr_login_server }}/redis:latest"
                ports:
                  - containerPort: 6379
                volumeMounts:
                  - mountPath: /data
                    name: redis-storage
            volumes:
              - name: redis-storage
                persistentVolumeClaim:
                  claimName: redis-pvc

- name: Create Redis service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: redis-service
        namespace: "{{ app_namespace }}"
      spec:
        selector:
          app: redis
        ports:
          - port: 6379
            targetPort: 6379
